src/Entity/Membre.php
<?php

namespace App\Entity;


use App\Repository\MembreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

use Doctrine\DBAL\Types\Types;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;

use Symfony\Component\Security\Core\User\UserInterface;


#[ORM\Entity(repositoryClass: MembreRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]

class Membre implements UserInterface, PasswordAuthenticatedUserInterface

{

    #[ORM\Id]

    #[ORM\GeneratedValue]

    #[ORM\Column]

    private int $id;


    #[ORM\Column(type: 'string', length: 180, unique: true)]

    private $email;


    #[ORM\Column(type: Types::JSON)]

    private $roles;


    /**

     * @var string The hashed password

     */

    #[ORM\Column(type: 'string', nullable: false, options: ["collation" => "utf8mb4_general_ci"])]

    private $password;


    #[ORM\Column(type: 'string', length: 20, nullable: false, options: ["collation" => "utf8mb4_general_ci"])]

    private $pseudo;


    #[ORM\Column(type: 'string', length: 20, nullable: false, options: ["collation" => "utf8mb4_general_ci"])]

    private $nom;


    #[ORM\Column(type: 'string', length: 20, nullable: false, options: ["collation" => "utf8mb4_general_ci"])]

    private $prenom;


    #[ORM\Column(length: 1, columnDefinition: "ENUM('m', 'f') NOT NULL DEFAULT 'm'", options: ["collation" => "utf8mb4"])]

    private $civilite;


    #[ORM\Column(type: 'string', length: 50, nullable: false, options: ["collation" => "utf8mb4_general_ci"])]

    private $ville;


    #[ORM\Column(type: 'integer')]

    private $code_postal;


    #[ORM\Column(type: 'string', length: 50, nullable: false, options: ["collation" => "utf8mb4_general_ci"])]

    private $adresse;


    #[ORM\Column(type: 'integer')]

    private $statut;


    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]

    private $date_enregistrement;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    #[ORM\OneToOne(targetEntity: Panier::class, mappedBy: 'membre')]
    private ?Panier $panier = null;

    #[ORM\ManyToMany(targetEntity: Coupon::class, inversedBy: 'membres')]
    private Collection $coupon;

    #[ORM\OneToMany(mappedBy: 'membre', targetEntity: Order::class, orphanRemoval: true)]
    private Collection $orders;

    public function __construct()
    {
        $this->coupon = new ArrayCollection();
        $this->orders = new ArrayCollection();
    }


    public function getId(): ?int

    {

        return $this->id;
    }


    public function getEmail(): ?string

    {

        return $this->email;
    }


    public function setEmail($email): self

    {

        $this->email = $email;


        return $this;
    }


    /**

     * A visual identifier that represents this user.

     *

     * @see UserInterface

     */

    public function getUserIdentifier(): string

    {

        return (string) $this->email;
    }


    /**

     * @see UserInterface

     */

    public function getRoles(): array

    {

        $roles = $this->roles;

        // guarantee every user at least has ROLE_USER

        $roles[] = 'ROLE_USER';


        return array_unique($roles);
    }


    public function setRoles($roles): self

    {

        $this->roles = $roles;


        return $this;
    }


    /**

     * @see PasswordAuthenticatedUserInterface

     */

    public function getPassword(): string

    {

        return $this->password;
    }


    public function setPassword($password): self

    {

        $this->password = $password;


        return $this;
    }


    /**

     * @see UserInterface

     */

    public function eraseCredentials()

    {

        // If you store any temporary, sensitive data on the user, clear it here

        // $this->plainPassword = null;

    }


    public function getPseudo(): ?string

    {

        return $this->pseudo;
    }


    public function setPseudo($pseudo): self

    {

        $this->pseudo = $pseudo;


        return $this;
    }


    public function getNom(): ?string

    {

        return $this->nom;
    }


    public function setNom($nom): self

    {

        $this->nom = $nom;


        return $this;
    }


    public function getPrenom(): ?string

    {

        return $this->prenom;
    }


    public function setPrenom($prenom): self

    {

        $this->prenom = $prenom;


        return $this;
    }


    public function getCivilite(): ?string

    {

        return $this->civilite;
    }


    public function setCivilite($civilite): self

    {

        $this->civilite = $civilite;


        return $this;
    }


    public function getVille(): ?string

    {

        return $this->ville;
    }


    public function setVille($ville): self

    {

        $this->ville = $ville;


        return $this;
    }


    public function getCodePostal(): ?int

    {

        return $this->code_postal;
    }


    public function setCodePostal($code_postal): self

    {

        $this->code_postal = $code_postal;


        return $this;
    }


    public function getAdresse(): ?string

    {

        return $this->adresse;
    }


    public function setAdresse($adresse): self

    {

        $this->adresse = $adresse;


        return $this;
    }


    public function getStatut(): ?int

    {

        return $this->statut;
    }


    public function setStatut($statut): self

    {

        $this->statut = $statut;


        return $this;
    }


    public function getDateEnregistrement(): ?\DateTimeInterface

    {

        return $this->date_enregistrement;
    }


    public function setDateEnregistrement($date_enregistrement): self

    {

        $this->date_enregistrement = $date_enregistrement;


        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    /**
     * @return Collection<int, Coupon>
     */
    public function getCoupon(): Collection
    {
        return $this->coupon;
    }

    public function addCoupon(Coupon $coupon): self
    {
        if (!$this->coupon->contains($coupon)) {
            $this->coupon->add($coupon);
        }

        return $this;
    }

    public function removeCoupon(Coupon $coupon): self
    {
        $this->coupon->removeElement($coupon);

        return $this;
    }

    public function setPanier(Panier $panier): self
    {
        $this->panier = $panier;

        return $this;
    }

    public function getPanier(): ?Panier
    {

        return $this->panier;
    }

    /**
     * @return Collection<int, Order>
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Order $order): self
    {
        if (!$this->orders->contains($order)) {
            $this->orders->add($order);
            $order->setMembre($this);
        }

        return $this;
    }

    public function removeOrder(Order $order): self
    {
        if ($this->orders->removeElement($order)) {
            // set the owning side to null (unless already changed)
            if ($order->getMembre() === $this) {
                $order->setMembre(null);
            }
        }

        return $this;
    }
}

src/Controller/PaypalController.php
<?php

namespace App\Controller;

use App\Entity\PaymentMethod;
use App\Service\PayPal;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use App\Service\AppHelpers;
use App\Service\OrderManager;
use App\Service\PanierManager;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\Security\Core\Security;
use Symfony\Component\HttpFoundation\RequestStack;

class PaypalController extends AbstractController
{
    private string $bodyId;
    private $app;
    private $db;
    private $userInfo;
    private $cartCount;
    private $session;

    public function __construct(Security $security, ManagerRegistry $doctrine,  AppHelpers $app, RequestStack $requestStack, PanierManager $cartManager,)
    {
        $this->app = $app;
        $this->bodyId = $app->getBodyId('ORDER_CONFIRMATION');
        $this->db = $doctrine->getManager();
        $this->userInfo = $app->getUser();
        $this->session = $requestStack->getSession();
        $this->session = $requestStack->getSession();
        if (null !== $this->userInfo->user) {
            if (null !== $this->session->get('cartCount')) {
                $this->cartCount = (int)$this->session->get('cartCount');
            } else {
                $this->session->set('cartCount', $cartManager->getCartCount($this->userInfo->user));
                $this->cartCount = (int)$this->session->get('cartCount');
            }
        }
    }

    public function index(PayPal $payPal): Response
    {
        if (!isset($this->session->get('checkoutData')['orderTotals']['totalTTC'])) {
            return $this->redirectToRoute('app_category');
        }

        $method = $this->db->getRepository(PaymentMethod::class)->find((int)$this->session->get('checkoutData')['payment']['method']);

        return $this->render('paypal/index.html.twig', [
            'bodyId' => $this->bodyId,
            'userInfo' => $this->userInfo,
            'cartCount' => $this->cartCount,
            'parameters' => $payPal->getQueryParametersForJsSdk(),
            'paymentMethod' => 'payPal Charge',
            'amount' => (float)$this->session->get('checkoutData')['orderTotals']['totalTTC'],
            'shipping_preference' => $this->session->get('checkoutData')['shippingMethod']['nom'],
            'checkoutData' => $this->session->get('checkoutData'),
            'method' => $method,
        ]);
    }

    public function orderConfirmation(OrderManager $om): Response
    {
        $totalOrder = $this->session->get('orderTotal');
        $om->cleanUpAfterCheckout();
        $this->session->set('cartCount', 0);

        return $this->render('paypal/order_confirmation.html.twig', [
            'bodyId' => $this->bodyId,
            'cartCount' => 0,
            'userInfo' => $this->userInfo,
            'orderTotal' => $totalOrder,
            'paymentMethod' => 'Stripe Charge',
        ]);
    }

    public function paymentFailure(Request $request, string $err, OrderManager $om): Response
    {
        return $this->render('paypal/payment_failure.html.twig', [
            'bodyId' => $this->bodyId,
            'cartCount' => $this->cartCount,
            'userInfo' => $this->userInfo,
            'orderTotal' => $this->session->get('orderTotal'),
            'error' => $err,
        ]);
    }
}

templates/paypal/index.html.twig
{% extends 'layout-full-width.html.twig' %}

{% block title %}Paiement Paypal
{% endblock %}

{% block contentFullWidth %}
	<div>
		<div class="container mt-4">
			<div class="row">
				<div class="col-md-6">
					<div class="container">
						<div class="row">
							<div class="col bg-light">
								<h4>
									Finalisation de ma commande
								</h4>
								<p>
									<small>Veuillez vérifier les informations fournies.</small>
								</p>
							</div>
						</div>

						<div class="vr"></div>

						<div class="row ">
							<div class="col bg-light">
								<h6>
									<em>Adresse de livraison</em>
								</h6>
								<p>{{ checkoutData.adresseLivraison.adresse }}<br>{{ checkoutData.adresseLivraison.codePostal }}
									{{ checkoutData.adresseLivraison.ville }}</p>
							</div>
						</div>

						<div class="vr"></div>

						<div class="row ">
							<div class="col bg-light">
								<h6>
									<em>Mode de livraison</em>
								</h6>
								<p>{{ checkoutData.shippingMethod.nom }}</p>
							</div>
						</div>

						<div class="vr"></div>

						<div class="row ">
							<div class="col bg-light">
								<h6>
									<em>Moyen de Paiement</em>
								</h6>
								<p>
									<img class="me-2" src="{{ asset('assets/img/'~ method.img) }}" width="{{ method.width }}" alt="payment method">
									<label class="form-check-label" for="paymentMethodOption{{ method.id }}">
										{{ method.name }}
									</label>
								</p>
							</div>
						</div>

					</div>
				</div>

				<div class="col-md-3 offset-3">
					<div class="container bg-light pb-4">
						<div class="row">
							<h4>Panier:</h4>
						</div>
						<div class="row mb-3">
							<div class="col-md-7 d-flex justify-content-end">
								<em>Total Articles HT:</em>
							</div>
							<div class="col-md-5 d-flex justify-content-end">
								{{ checkoutData.orderTotals.cartTotals.totalHT|format_currency('EUR') }}
							</div>
						</div>

						<div class="row pb-2 mb-1 border-0 border-bottom">
							<div class="col-md-7 d-flex justify-content-end">
								<em>Livraison:</em>
								<span style="color:red;">*</span>
							</div>
							<div class="col-md-5 d-flex justify-content-end">
								{{ checkoutData.orderTotals.totalLivraisonHT|format_currency('EUR') }}
							</div>
						</div>

						<div class="row mb-3">
							<div class="col-md-7 d-flex justify-content-end">
								<em>Total HT:</em>
							</div>
							<div class="col-md-5 d-flex justify-content-end">
								{{ (checkoutData.orderTotals.cartTotals.totalHT + checkoutData.orderTotals.totalLivraisonHT)|format_currency('EUR') }}
							</div>
						</div>

						<div class="row mb-3 border-0 border-bottom">
							<div class="col-md-7 d-flex justify-content-end">
								<em>TVA(20%):</em>
							</div>
							<div class="col-md-5 d-flex justify-content-end pb-2">
								{{ checkoutData.orderTotals.tva20|format_currency('EUR') }}
							</div>
						</div>

						<div class="row  mb-3">
							<div class="col-md-7 d-flex justify-content-end">
								Total TTC:
							</div>
							<div class="col-md-5 d-flex justify-content-end">
								<strong>
									{{ checkoutData.orderTotals.totalTTC|format_currency('EUR') }}
								</strong>
							</div>
						</div>
						<div class="row  mb-3">
							<div class="col d-flex justify-content-start">
								<span style="color:red;">*</span>
								<span class="text-secondary">
									<small>{{ checkoutData.shippingMethod.nom }}</small>
								</span>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="checkout-step" data-step="4"></div>
		<div class="container">
			<div class="row justify-content-center">
				<div
					class="col-6 mx-auto mt-5">

					{# payPal Payment Element #}
					<div id="paypal-button-container"></div>

				</div>
			</div>
		</div>
		<div class="container">
			<div class="row">
				<div class="col border-top border-secondary mt-5 d-flex justify-content-between pt-3">
					<a class="btn btn-outline-dark cart-btn d-inline-block" href="{{ absolute_url(path('app_order', {step: 3})) }}" role="button">Etape précédente</a>
				</div>
			</div>
		</div>
		<script src="https://www.paypal.com/sdk/js?{{ parameters }}"></script>
		<script>
			paypal.Buttons({ // All your options here !
createOrder: (data, actions) => {
return actions.order.create({
intent: 'capture', // capture or authorize
purchase_units: [
{
amount: {
value: {{ amount }}
},
description: 'Fake-Paris Customer Order',
// invoice_id: '1234567890',
// soft_descriptor: 'unicorn-2345678'
}
],
application_context: { // brand_name: 'My amazing brand',
shipping_preference: 'NO_SHIPPING' // if you handle shipping
}
});
},
// Finalizes the transaction after payer approval
onApprove: (data) => { // error = err.purchase_units.captures.status;
window.location.assign("{{ absolute_url(path('app_paypal_success')) }}");
},
// The user closed the window
onCancel: () => {},
onError: (err) => {
error = err.purchase_units.captures.status;
window.location.assign("{{ absolute_url(path('app_paypal_fail', {err: ''})) }}/" + error);
}
}).render('#paypal-button-container');
		</script>

	{% endblock %}

templates/paypal/order_confirmation.html.twig
{% extends 'layout-full-width.html.twig' %}

{% block title %}Confirmation
{% endblock %}

{% block contentFullWidth %}
	<div>
		<div class="mt-5 p-5 border border-primary d-flex flex-column justify-content-center align-items-center">
			<h3>Votre commande est complete!!</h3>
			<h5>Merci de votre confiance.</h5>
			<h5>montant régle:
				{{ orderTotal }}€</h5>
			<a class="btn btn-outline-primary mt-3" href="{{ path('app_home') }}">Retour à la boutique</a>
		</div>
	</div>
{% endblock %}

templates/paypal/payment_failure.html.twig
{% extends 'layout-full-width.html.twig' %}

{% block title %}Confirmation
{% endblock %}

{% block contentFullWidth %}
	<div>
		<div class="mt-5 p-5 border border-primary d-flex flex-column justify-content-center align-items-center">
			<h3>Nous somme désolé, le service de paiement nous a retourné la réponse suivante:</h3>
			<h4 class="fw-bold text-danger">{{ error }}</h4>
			<a class="btn btn-outline-primary mt-3" href="{{ path('app_stripe') }}">Retour à la page de paiement</a>
		</div>
	</div>
{% endblock %}